/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Linear Dark Theme */
        canvas: 'var(--canvas)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-4': 'var(--surface-4)',
        ink: 'var(--ink)',
        'ink-muted': 'var(--ink-muted)',
        'ink-subtle': 'var(--ink-subtle)',
        'ink-tertiary': 'var(--ink-tertiary)',
        hairline: 'var(--hairline)',
        'hairline-strong': 'var(--hairline-strong)',
        'hairline-tertiary': 'var(--hairline-tertiary)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-focus': 'var(--accent-focus)',
        success: 'var(--success)',
        error: 'var(--error)',
        warning: 'var(--warning)',

        /* Auth Light Theme */
        'auth-canvas': 'var(--auth-canvas)',
        'auth-surface': 'var(--auth-surface)',
        'auth-ink': 'var(--auth-ink)',
        'auth-ink-muted': 'var(--auth-ink-muted)',
        'auth-hairline': 'var(--auth-hairline)',
        'auth-accent': 'var(--auth-accent)',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.05', letterSpacing: '-1.5px', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '1.1', letterSpacing: '-1px', fontWeight: '600' }],
        'display-md': ['28px', { lineHeight: '1.15', letterSpacing: '-0.5px', fontWeight: '600' }],
        'display-sm': ['22px', { lineHeight: '1.25', letterSpacing: '-0.3px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.5', letterSpacing: '-0.05px', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'button': ['14px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'eyebrow': ['13px', { lineHeight: '1.3', letterSpacing: '0.4px', fontWeight: '500' }],
        'mono': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'xxl': '24px',
        'pill': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '96px',
      },
      boxShadow: {
        'card': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'card-hover': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'elevated': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
}